# .github/workflows/build-mac.yml
name: Build Mac App

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build Mac App
        run: pyinstaller --onefile --windowed --icon=study.icns --name=학습폰 학습폰.py


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/*
